version: '3.7'

services:
  todo:
    build: .
    ports:
      - 3001:3001
    environment:
      DATABASE_HOST: mongo
      DATABASE_USERNAME: todo
      DATABASE_PASSWORD: todo

  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    restart: always
    volumes:
      - mongo_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

volumes:
  mongo_data: